# Generated by Django 5.0.14 on 2026-06-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inquiry_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='products.product'),
        ),
    ]
